# Generated by Django 6.1 on 2026-09-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
