# Generated by Django 6.1 on 2026-09-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_estimated_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_hours',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
